# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Lydia's notes
subtitle: 'Tips about Python and Linux.'
description: 'Tips about Python and Linux.'
keywords: 'python, coding'
author: Lydia Zhang
language: en
timezone: 'America/Vancouver'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://lydiazly.github.io
permalink: :year-:month-:day-:title.html
permalink_defaults:
  lang: en
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - googlea24ada8f7c1fd278.html
  - BingSiteAuth.xml

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked: # hexo-renderer-marked
  gfm: true # Enables GitHub flavored markdown
  breaks: true # Enable GFM line breaks. This option requires the gfm option to be true.
  autolink: true
  prependRoot: true
  postAsset: true
  # external_link:
  #   enable: true # Open external links in a new tab.
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  line_threshold: 0
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:lydiazly/lydiazly.github.io.git

# hexo-generator-tag
tag_generator:
  enable_index_page: false

# hexo-renderer-markdown-it
# markdown:
#   # preset: 'default'
#   render:
#     html: true
#     xhtmlOut: false
#     langPrefix: 'language-'
#     breaks: true
#     linkify: true
#     typographer: false
#   plugins:
#     - markdown-it-abbr
#     - markdown-it-cjk-breaks
#     - markdown-it-deflist
#     # - markdown-it-emoji
#     - markdown-it-footnote
#     - markdown-it-ins
#     - markdown-it-mark
#     - markdown-it-sub
#     - markdown-it-sup
#     # - markdown-it-checkbox
#     # - markdown-it-imsize
#     # - markdown-it-expandable
#     # - name: markdown-it-container
#     #   options: success
#     # - name: markdown-it-container
#     #   options: tips
#     # - name: markdown-it-container
#     #   options: warning
#     # - name: markdown-it-container
#     #   options: danger
#   anchors:
#     level: 2
#     collisionSuffix: ''
#     permalink: false
#     permalinkClass: 'header-anchor'
#     permalinkSide: 'left'
#     permalinkSymbol: '¶'
#     case: 0
#     separator: '-'

# RSS
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

# hexo-broken-links-checker
# broken_links_checker:
#     enable: true
#     head: true
#     frontmatter:
#         - links
#     exclude:
#     timeout: 3000
#     useragent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'
#     parallel: 10
#     tags:
#         a: true
#         img: true
#         source: true
#         iframe: true
#         script: true
#         link: true
#     cache:
#         enable: true
#         lifetime: 1440
#         path: 'link-checker.json'

# hexo-renderer-pandoc
pandoc:
  # template: ./source/templates/pandoc-template.html
  extra:
    # - from: gfm
    - lua-filter: ./source/filter/anchor-links.lua
